## use numpy

In [2]:
import numpy as np

---

## 0 D

In [23]:
a = np.array(11)

In [24]:
print(a)

11


## return dimensional by ndim method

In [25]:
a.ndim

0

## 1D

In [4]:
a = np.array([1,2,3])

In [5]:
print(a)

[1 2 3]


In [ ]:
a2 = np.array(
    [1,2,3]
)

In [6]:
type(a)

numpy.ndarray

In [7]:
a.ndim

1

In [8]:
a

array([1, 2, 3])

## 2 D

In [10]:
b1 = np.array([[1,2],[3,4]])
print(b)

[[1 2]
 [3 4]]


In [11]:
b1.ndim

2

In [12]:
b2 = np.array(
    [
        [1,2,3],
        [1,2,3]
    ]
)

In [27]:
b3 = np.array(
    [
        [1,2,3],
        [3,4,7],
        [5,6,9]
    ]
)

## 3 D

In [21]:
c = np.array([[[11,8],[2,3]],[[1,4],[5,6]]])

In [14]:
c1 = np.array(
    [
        [
            [1,2,3],
            [1,2,3]
        ],
        [
            [1,2,3],
            [1,2,3]
        ]
    ]
)


In [15]:
c2 = np.array(
    [
        [
            [1]
        ]
    ]
)

In [16]:
a.ndim

3

## shape method

In [29]:
c2 = np.array(
    [
        [
            [1]
        ]
    ]
)

In [30]:
c2.shape

(1, 1, 1)

In [34]:
c1 = np.array(
    [
        [
            [1,2,3,4],
            [1,2,3,4],
            [11,2,3,4]
        ],
        [
            [1,2,3,4],
            [1,2,3,4],
            [1,2,3,4]
        ]
    ]
)


In [35]:
c1.shape

(2, 3, 4)

## scalars

In [36]:
a = np.array([1, 2.3])
a

array([1. , 2.3])

In [37]:
a1 = np.array([1], 'amir')
a1

TypeError: data type 'amir' not understood

In [3]:
a2 = np.array([1, 'true'])
a2

array(['1', 'true'], dtype='<U21')

In [4]:
a3 = np.array([1, True])
a3

array([1, 1])

In [3]:
a4 = np.array([True, 'amir'])
a4

array(['True', 'amir'], dtype='<U5')

## datatype in array

In [6]:
a5 = np.array([1, 2, 3], dtype = np.uint8)

## dtype method

In [7]:
a5.dtype

dtype('uint8')