In [2]:
import numpy as np

In [3]:
a = np.array([[1, 2],
            [3, 4],
            [5, 6]
             ])

## size method

In [4]:
a.size

6

## reshape method

In [6]:
a.shape

(3, 2)

In [7]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
b = a.reshape(1, 6)
b

array([[1, 2, 3, 4, 5, 6]])

In [10]:
c = a.reshape(2, 3, 1)
c

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [11]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

## slicing array

In [12]:
a[1]

array([3, 4])

## slicing in python

In [14]:
a[1][1]

np.int64(4)

## slicing in python

In [18]:
a[1, 1]

np.int64(4)

In [21]:
a[0:2]

array([[1, 2],
       [3, 4]])